# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0002_auto_20160716_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='category',
            field=models.CharField(default='no category', max_length=30),
        ),
    ]
