# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0003_word_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='description',
            field=models.CharField(default='', max_length=300),
        ),
    ]
