# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0005_auto_20161029_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='picture',
            field=models.CharField(default='', max_length=500),
        ),
    ]
