# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-03 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0007_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='other', max_length=30),
        ),
    ]
