# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0010_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
